### ISSUE TITLE
Under which license the code is released?

### ISSUE THREAD

**Issue by traversaro** [OriginDelight/EllipseFit#1]
Hi @seisgo, thanks for the nice open source code contained in this repository! 

It would be great if you could document under which software license (see https://choosealicense.com/ and https://help.github.com/en/articles/licensing-a-repository) this code is released.

**Comment by seisgo** [comment]
Hi @traversaro, thanks for your comment, this repository is licensed under MIT, please feel free to use it.

**Comment by traversaro** [comment]
Sorry @seisgo , for some reason I missed the file in https://github.com/seisgo/EllipseFit/blob/a2e30fca3b4ae7e2353b73cfc20c057a20d132fb/LICENSE , thanks for the kind reply!
