### ISSUE TITLE
RANSAC filtering function is not correct

### ISSUE THREAD

**Issue by nishbo** [OriginDelight/EllipseFit#2]
RANSAC filtering on each iteration is supposed to choose a minimal number of points to fit a model of ellipse and measure which other points agree with this model (inliers). In the current implementation, on each iteration, 3 datapoints are chosen, and two of them are treated as focal points of an ellipse. That is incorrect, because the goal is to identify the ellipse parameters from the sampled points, including the focal points.
In a general case, one needs at least 5 points to define an ellipse, less if there is info on the center:
https://math.stackexchange.com/questions/880258/minimal-number-of-points-to-define-a-rotated-ellipse
A possible solution is to change the function to sample 4 points (without replacement) from dataset. Use them to estimate the two foci, e.g. using one of the funcEllipseFit functions. That can be used to measure the distance from each of the sample points to the foci. All datapoints which distance to the foci is close to the average sample distance can be treated as 'inliers'.

**Comment by seisgo** [comment]
Hi, @nishbo , thanks for pointing out this problem. 
I have reviewed my code in _ellipseDataFilter_RANSAC.m_, the implementation actually is not "[random sample consensus](https://en.wikipedia.org/wiki/Random_sample_consensus)", but just a preparation of data for ellipse fitting. I am sorry for this misconception.
Just as well, this repository is mainly about ellipse fitting, and those implementations perform well.
