### ISSUE TITLE
无法找到源文件algo_global.h

### ISSUE THREAD

**Issue by zzg-tju** [OriginDelight/EllipseFit#3]
大佬您好，我刚刚接触C++不久，在配置环境这里一直是懵懵的。想借鉴你的代码实现瞳孔检测中的椭圆拟合，但是遇到了 **无法找到源文件algo_global.h** 的问题，同时提示无法打开源文件QVector，希望你能指点我一下。
环境为vs2017，QT5.12.1，clapack库已经配置好。
![image](https://user-images.githubusercontent.com/54742833/85110340-595d5d80-b245-11ea-994f-5b9cca7008d4.png)

**Comment by zhubingHIT** [comment]
如果仅仅是拟合，你用opencv里面的椭圆拟合就可以。



在 2020-06-19 14:56:45，"zzg-tju" <notifications@github.com> 写道：

大佬您好，我刚刚接触C++不久，在配置环境这里一直是懵懵的。想借鉴你的代码实现瞳孔检测中的椭圆拟合，但是遇到了 无法找到源文件algo_global.h 的问题，同时提示无法打开源文件QVector，希望你能指点我一下。
环境为vs2017，QT5.12.1，clapack库已经配置好。

**Comment by seisgo** [comment]
> 大佬您好，我刚刚接触C++不久，在配置环境这里一直是懵懵的。想借鉴你的代码实现瞳孔检测中的椭圆拟合，但是遇到了 **无法找到源文件algo_global.h** 的问题，同时提示无法打开源文件QVector，希望你能指点我一下。
> 环境为vs2017，QT5.12.1，clapack库已经配置好。
> ![image](https://user-images.githubusercontent.com/54742833/85110340-595d5d80-b245-11ea-994f-5b9cca7008d4.png)

你好，不客气，欢迎使用。
algo_global.h这个引用是我大工程里面的一个设置，为了实现Linux和Windows的 跨平台兼容，跟算法不相关。
请你在编译时将其删除掉，同时也删除掉“class EP_ALGO_EXPORT Ellipse”中间的EP_ALGO_EXPORT宏。稍后我也把GitHub上面修改一下。

关于QVector的问题，可以再确认一下VS的Qt库的配置，我使用QtCreator上直接编译的。

我写这个代码主要是为了能够相对低耦合的实现椭圆拟合，方便应用到自己的项目中。另外，这个算法能够对各种样点分布给出一个拟合的椭圆结果，而不会由于样点分布形态为双曲线或其他圆锥曲线而拟合失败。

**Comment by zzg-tju** [comment]
> 如果仅仅是拟合，你用opencv里面的椭圆拟合就可以。 在 2020-06-19 14:56:45，"zzg-tju" <notifications@github.com> 写道： 大佬您好，我刚刚接触C++不久，在配置环境这里一直是懵懵的。想借鉴你的代码实现瞳孔检测中的椭圆拟合，但是遇到了 无法找到源文件algo_global.h 的问题，同时提示无法打开源文件QVector，希望你能指点我一下。 环境为vs2017，QT5.12.1，clapack库已经配置好。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

原来OpenCv里已经把算法封装好了，非常感谢！

**Comment by zzg-tju** [comment]
> > 大佬您好，我刚刚接触C++不久，在配置环境这里一直是懵懵的。想借鉴你的代码实现瞳孔检测中的椭圆拟合，但是遇到了 **无法找到源文件algo_global.h** 的问题，同时提示无法打开源文件QVector，希望你能指点我一下。
> > 环境为vs2017，QT5.12.1，clapack库已经配置好。
> > ![image](https://user-images.githubusercontent.com/54742833/85110340-595d5d80-b245-11ea-994f-5b9cca7008d4.png)
> 
> 你好，不客气，欢迎使用。
> algo_global.h这个引用是我大工程里面的一个设置，为了实现Linux和Windows的 跨平台兼容，跟算法不相关。
> 请你在编译时将其删除掉，同时也删除掉“class EP_ALGO_EXPORT Ellipse”中间的EP_ALGO_EXPORT宏。稍后我也把GitHub上面修改一下。
> 
> 关于QVector的问题，可以再确认一下VS的Qt库的配置，我使用QtCreator上直接编译的。
> 
> 我写这个代码主要是为了能够相对低耦合的实现椭圆拟合，方便应用到自己的项目中。另外，这个算法能够对各种样点分布给出一个拟合的椭圆结果，而不会由于样点分布形态为双曲线或其他圆锥曲线而拟合失败。

非常感谢你的回答！
